# XOR operation by Neural network

In [2]:
# Implement code for Sung Kim's TF lecture. See https://www.youtube.com/watch?v=9i7FBbcZPMA&feature=youtu.be

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

# Need to change data structure. THESE LINES ARE DIFFERNT FROM Video BUT IT MAKES THIS CODE WORKS!
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )




0 0.709144 [[-0.65679926 -0.18958679]
 [ 0.12794963  0.81384182]] [[ 0.61581868]
 [ 0.16675976]]
1000 0.692954 [[-0.68498749 -0.1935062 ]
 [ 0.21847157  0.81189352]] [[ 0.50370032]
 [-0.04746513]]
2000 0.69239 [[-0.76409727 -0.22777221]
 [ 0.34441516  0.83107841]] [[ 0.54096526]
 [-0.13836476]]
3000 0.689815 [[-0.98998111 -0.31162232]
 [ 0.5799312   0.88689882]] [[ 0.71053863]
 [-0.27915817]]
4000 0.65986 [[-1.78624308 -0.58519751]
 [ 1.36011374  1.1108408 ]] [[ 1.48578203]
 [-0.67106932]]
5000 0.377295 [[-3.68406963 -2.24369097]
 [ 3.40342522  2.6310904 ]] [[ 3.9781363 ]
 [-2.76237702]]
6000 0.117037 [[-4.84093666 -4.04099655]
 [ 4.65694475  4.34624577]] [[ 6.25426626]
 [-5.48781013]]
7000 0.0585975 [[-5.34939718 -4.76098967]
 [ 5.17598963  5.04990721]] [[ 7.4919095 ]
 [-6.86068201]]
8000 0.0378506 [[-5.64535856 -5.15269041]
 [ 5.4703517   5.43505526]] [[ 8.28090858]
 [-7.69874763]]
[array([[ 0.03660639],
       [ 0.96825677],
       [ 0.95039552],
       [ 0.03049923]], dtype=float32

# Use 'wide' neural network to solve XOR problem. 

In [3]:
# Use 'wide' neural network (10 neurals) to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Wide network: Use more neurons in each layer. 
W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )


0 0.810507 [[ 0.03593338  0.4675028  -0.42452276 -0.30866268 -0.41931269 -0.19097252
   0.55209386 -0.20426369  0.60859221  0.18376905]
 [-0.38751897  0.5298183   0.65148044  0.4019376  -0.98497581 -0.66995054
   0.6445483   0.09752972 -0.11443435  0.05719196]] [[-0.22138293]
 [ 0.93023342]
 [ 0.67608792]
 [-0.97943372]
 [ 0.7728014 ]
 [ 0.86023867]
 [ 0.82027453]
 [ 0.98739898]
 [-0.73849207]
 [-0.95119607]]
1000 0.641755 [[ 0.05025027  1.21516097 -0.62710214 -0.41050568 -0.0467158   0.02585443
   1.4461323  -0.31560913  0.87403572  0.26281512]
 [-0.33627656  1.23621917  0.5247643   0.88591051 -0.91700304 -0.71362042
   1.4789753   0.03446257 -0.28335595  0.11519052]] [[-0.41277894]
 [ 1.16270149]
 [ 0.49080515]
 [-1.38072681]
 [ 0.52689135]
 [ 0.69237918]
 [ 1.33279753]
 [ 0.78498822]
 [-1.11178041]
 [-1.22122526]]
2000 0.348656 [[ 0.35511255  2.50769186 -1.19076037 -1.56640136 -0.03631353 -0.02362451
   3.03516722 -0.71926391  2.27211785  0.79789889]
 [-0.09907293  2.56422043  0.489

# Use 'Deep' neural network to solve XOR problem. 

In [4]:
# Use 'Deep' neural network to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Deep network configuration.: Use more layers. 
W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))


b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")


# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )

0 0.696978 [[ 0.24734968  0.60207188 -0.77929091  0.45870537  0.18110394]
 [-0.52320302 -0.00692286  0.70473975 -0.8925215   0.49226522]] [[ 0.48073024  0.69555891  0.29164037 -0.12338613]
 [-0.65053785 -0.58052325 -0.70374703 -0.1465831 ]
 [-0.04056193 -0.64179486 -0.55849057 -0.47276947]
 [-0.74256682 -0.08953542  0.54299819  0.2098498 ]
 [ 0.11086085 -0.83629286 -0.56223291  0.31209701]]
1000 0.693104 [[ 0.22065221  0.62755555 -0.78546333  0.45835552  0.2464716 ]
 [-0.51060456  0.00190646  0.68009019 -0.88174552  0.50345755]] [[ 0.48043922  0.67925894  0.28510249 -0.12252576]
 [-0.65171254 -0.60347241 -0.71186894 -0.14643791]
 [-0.03730871 -0.62244809 -0.55152881 -0.4728106 ]
 [-0.74094552 -0.12258816  0.52983594  0.21229534]
 [ 0.11235784 -0.84888464 -0.56649983  0.31246713]]
2000 0.69298 [[ 0.19560717  0.65167588 -0.79525042  0.46016544  0.31483936]
 [-0.500799    0.01445571  0.66353071 -0.8742981   0.52380908]] [[ 0.47899938  0.67058802  0.28181773 -0.12198969]
 [-0.65402889 -0.6